### ISSUE TITLE
ARM installation failed

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/wekan_ynh#1]
Hello,
Meteor is not for arm for now as that is written when I install it : "Meteor only supports i686 and x86_64 for now."

log of installation (a part--the end): 
```
[...](compilation of npm)
2017-04-11 23:39:12,507 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8-profiler.h
2017-04-11 23:39:12,509 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8.h
2017-04-11 23:39:12,511 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8-testing.h
2017-04-11 23:39:12,514 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8-debug.h
2017-04-11 23:39:12,516 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8stdint.h
2017-04-11 23:39:12,518 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/v8-preparser.h
2017-04-11 23:39:12,521 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/zconf.h
2017-04-11 23:39:12,523 INFO     yunohost.hook <lambda> - [1144.174] installing /opt/nvm/v0.10.48/include/node/zlib.h
2017-04-11 23:39:20,285 INFO     yunohost.hook <lambda> - [1144.174] Now using node v0.10.48 (npm v2.15.1)
2017-04-11 23:39:20,910 WARNING  yunohost.hook <lambda> - [1144.174] tput: unknown terminal "unknown"
2017-04-11 23:39:20,922 INFO     yunohost.hook <lambda> - [1144.174] Creating default alias: default -> 0.10 (-> v0.10.48 *)
2017-04-11 23:39:21,110 INFO     yunohost.hook <lambda> - [1144.174] + add_swap_if_needed
2017-04-11 23:39:21,116 INFO     yunohost.hook <lambda> - [1144.174] ++ free
2017-04-11 23:39:21,120 INFO     yunohost.hook <lambda> - [1144.174] ++ tail -n 1
2017-04-11 23:39:21,131 INFO     yunohost.hook <lambda> - [1144.174] ++ awk '{print $2}'
2017-04-11 23:39:21,170 INFO     yunohost.hook <lambda> - [1144.174] + local available_swap=1048572
2017-04-11 23:39:21,173 INFO     yunohost.hook <lambda> - [1144.174] + local tmp_swap_file=/tmp/wekan_swapfile
2017-04-11 23:39:21,176 INFO     yunohost.hook <lambda> - [1144.174] + '[' 1048572 -lt 1000000 ']'
2017-04-11 23:39:21,179 INFO     yunohost.hook <lambda> - [1144.174] + install_meteor
2017-04-11 23:39:21,182 INFO     yunohost.hook <lambda> - [1144.174] + '[' '!' -d /opt/meteor ']'
2017-04-11 23:39:21,185 INFO     yunohost.hook <lambda> - [1144.174] + sudo mkdir /opt/meteor
2017-04-11 23:39:21,354 INFO     yunohost.hook <lambda> - [1144.174] + sudo chown -R wekan /opt/meteor
2017-04-11 23:39:21,473 INFO     yunohost.hook <lambda> - [1144.174] + cd /opt/meteor
2017-04-11 23:39:21,476 INFO     yunohost.hook <lambda> - [1144.174] + sudo su -c 'curl https://install.meteor.com/ | sh'
2017-04-11 23:39:21,825 WARNING  yunohost.hook <lambda> - [1144.174]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2017-04-11 23:39:21,828 WARNING  yunohost.hook <lambda> - [1144.174]                                  Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0   6229      0 --:--:--  0:00:01 --:--:--  6233
2017-04-11 23:39:23,093 WARNING  yunohost.hook <lambda> - [1144.174] Unusable architecture: armv7l
2017-04-11 23:39:23,096 WARNING  yunohost.hook <lambda> - [1144.174] Meteor only supports i686 and x86_64 for now.
2017-04-11 23:39:23,287 INFO     yunohost.hook hook_exec - [1144.174] Exécution du script « /var/cache/yunohost/from_file/wekan_ynh-master/scripts/remove »...
2017-04-11 23:39:23,440 INFO     yunohost.hook <lambda> - [1144.174] + source /usr/share/yunohost/helpers
2017-04-11 23:39:23,448 INFO     yunohost.hook <lambda> - [1144.174] +++ run-parts --list /usr/share/yunohost/helpers.d
2017-04-11 23:39:23,457 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,460 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
2017-04-11 23:39:23,462 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/filesystem
2017-04-11 23:39:23,464 INFO     yunohost.hook <lambda> - [1144.174] +++ CAN_BIND=1
2017-04-11 23:39:23,468 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,471 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
2017-04-11 23:39:23,473 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/ip
2017-04-11 23:39:23,476 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,479 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
2017-04-11 23:39:23,481 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/mysql
2017-04-11 23:39:23,483 INFO     yunohost.hook <lambda> - [1144.174] +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
2017-04-11 23:39:23,486 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,488 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
2017-04-11 23:39:23,491 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/package
2017-04-11 23:39:23,493 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,496 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
2017-04-11 23:39:23,499 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/print
2017-04-11 23:39:23,501 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,504 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
2017-04-11 23:39:23,507 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/setting
2017-04-11 23:39:23,509 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,512 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
2017-04-11 23:39:23,514 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/string
2017-04-11 23:39:23,516 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,519 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
2017-04-11 23:39:23,521 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/user
2017-04-11 23:39:23,523 INFO     yunohost.hook <lambda> - [1144.174] ++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
2017-04-11 23:39:23,525 INFO     yunohost.hook <lambda> - [1144.174] ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
2017-04-11 23:39:23,527 INFO     yunohost.hook <lambda> - [1144.174] ++ . /usr/share/yunohost/helpers.d/utils
2017-04-11 23:39:23,528 INFO     yunohost.hook <lambda> - [1144.174] + readonly APP=wekan
2017-04-11 23:39:23,530 INFO     yunohost.hook <lambda> - [1144.174] + APP=wekan
2017-04-11 23:39:23,532 INFO     yunohost.hook <lambda> - [1144.174] ++ ynh_app_setting_get '' domain
2017-04-11 23:39:23,535 INFO     yunohost.hook <lambda> - [1144.174] ++ sudo yunohost app setting '' domain --output-as plain --quiet
2017-04-11 23:39:24,717 INFO     yunohost.hook <lambda> - [1144.174] + readonly DOMAIN=
2017-04-11 23:39:24,720 INFO     yunohost.hook <lambda> - [1144.174] + DOMAIN=
2017-04-11 23:39:24,723 INFO     yunohost.hook <lambda> - [1144.174] + readonly APP_INSTALL_PATH=/var/www/wekan
2017-04-11 23:39:24,726 INFO     yunohost.hook <lambda> - [1144.174] + APP_INSTALL_PATH=/var/www/wekan
2017-04-11 23:39:24,729 INFO     yunohost.hook <lambda> - [1144.174] + readonly NVM_INSTALL_DIR=/opt/nvm
2017-04-11 23:39:24,731 INFO     yunohost.hook <lambda> - [1144.174] + NVM_INSTALL_DIR=/opt/nvm
2017-04-11 23:39:24,734 INFO     yunohost.hook <lambda> - [1144.174] + readonly METEOR_INSTALL_DIR=/opt/meteor
2017-04-11 23:39:24,737 INFO     yunohost.hook <lambda> - [1144.174] + METEOR_INSTALL_DIR=/opt/meteor
2017-04-11 23:39:24,740 INFO     yunohost.hook <lambda> - [1144.174] + remove_node
2017-04-11 23:39:24,742 INFO     yunohost.hook <lambda> - [1144.174] + '[' -d /opt/nvm ']'
2017-04-11 23:39:24,745 INFO     yunohost.hook <lambda> - [1144.174] + sudo rm -rf /opt/nvm
2017-04-11 23:39:25,259 INFO     yunohost.hook <lambda> - [1144.174] + remove_meteor
2017-04-11 23:39:25,262 INFO     yunohost.hook <lambda> - [1144.174] + '[' -d /opt/meteor ']'
2017-04-11 23:39:25,265 INFO     yunohost.hook <lambda> - [1144.174] + sudo rm -rf /opt/meteor
2017-04-11 23:39:25,367 INFO     yunohost.hook <lambda> - [1144.174] + remove_wekan
2017-04-11 23:39:25,370 INFO     yunohost.hook <lambda> - [1144.174] + '[' -d /var/www/wekan ']'
2017-04-11 23:39:28,191 INFO     yunohost.hook <lambda> - [1144.174] + remove_mongodb
2017-04-11 23:39:28,194 INFO     yunohost.hook <lambda> - [1144.174] + sudo systemctl stop mongod
2017-04-11 23:39:28,339 WARNING  yunohost.hook <lambda> - [1144.174] Failed to stop mongod.service: Unit mongod.service not loaded.
2017-04-11 23:39:28,367 INFO     yunohost.hook <lambda> - [1144.174] + sudo systemctl disable mongod
2017-04-11 23:39:29,222 INFO     yunohost.hook <lambda> - [1144.174] + sudo apt-get remove -y mongodb-org=3.2.11 mongodb-org-server=3.2.11 mongodb-org-shell=3.2.11 mongodb-org-mongos=3.2.11 mongodb-org-tools=3.2.11
2017-04-11 23:39:29,494 INFO     yunohost.hook <lambda> - [1144.174] Lecture des listes de paquets…
2017-04-11 23:39:31,847 INFO     yunohost.hook <lambda> - [1144.174] Construction de l'arbre des dépendances…
2017-04-11 23:39:31,876 INFO     yunohost.hook <lambda> - [1144.174] Lecture des informations d'état…
2017-04-11 23:39:32,503 WARNING  yunohost.hook <lambda> - [1144.174] E: Impossible de trouver le paquet mongodb-org
2017-04-11 23:39:32,507 WARNING  yunohost.hook <lambda> - [1144.174] E: Impossible de trouver le paquet mongodb-org-server
2017-04-11 23:39:32,511 WARNING  yunohost.hook <lambda> - [1144.174] E: Impossible de trouver le paquet mongodb-org-shell
2017-04-11 23:39:32,514 WARNING  yunohost.hook <lambda> - [1144.174] E: Impossible de trouver le paquet mongodb-org-mongos
2017-04-11 23:39:32,517 WARNING  yunohost.hook <lambda> - [1144.174] E: Impossible de trouver le paquet mongodb-org-tools
2017-04-11 23:39:32,532 INFO     yunohost.hook <lambda> - [1144.174] + sudo apt-get update
2017-04-11 23:39:33,137 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://repo.yunohost.org jessie InRelease
2017-04-11 23:39:33,140 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie InRelease
2017-04-11 23:39:33,188 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie InRelease
2017-04-11 23:39:33,331 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://repo.yunohost.org jessie/stable armhf Packages
2017-04-11 23:39:33,369 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/main armhf Packages
2017-04-11 23:39:33,454 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/contrib armhf Packages
2017-04-11 23:39:33,471 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 1 http://httpredir.debian.org jessie-backports InRelease [166 kB]
2017-04-11 23:39:33,527 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie/main armhf Packages
2017-04-11 23:39:33,535 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/non-free armhf Packages
2017-04-11 23:39:33,631 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/rpi armhf Packages
2017-04-11 23:39:33,701 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie/ui armhf Packages
2017-04-11 23:39:33,864 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports InRelease
2017-04-11 23:39:34,293 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 2 http://httpredir.debian.org jessie-backports/main Translation-en [605 kB]
2017-04-11 23:39:34,465 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-fr_FR
2017-04-11 23:39:34,601 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-fr
2017-04-11 23:39:34,767 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-en
2017-04-11 23:39:35,829 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 3 http://httpredir.debian.org jessie-backports/main armhf Packages [846 kB]
2017-04-11 23:39:35,985 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 4 https://packages.gitlab.com jessie InRelease [23,2 kB]
2017-04-11 23:39:36,600 INFO     yunohost.hook <lambda> - [1144.174] Atteint https://packages.gitlab.com jessie/main Sources
2017-04-11 23:39:37,112 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 5 https://packages.gitlab.com jessie/main armhf Packages [15,9 kB]
2017-04-11 23:39:37,361 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 6 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:39:37,591 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 7 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:39:37,776 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports/main Translation-fr_FR
2017-04-11 23:39:37,813 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 8 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:39:37,864 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports/main Translation-fr
2017-04-11 23:39:38,098 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 9 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:39:38,333 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 10 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:39:38,583 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 11 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:39:38,630 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-fr_FR
2017-04-11 23:39:38,708 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-fr
2017-04-11 23:39:38,786 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
2017-04-11 23:39:38,830 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 12 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:39:38,872 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-fr_FR
2017-04-11 23:39:38,951 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-fr
2017-04-11 23:39:39,029 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-en
2017-04-11 23:39:39,071 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-fr_FR
2017-04-11 23:39:39,075 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 13 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:39:39,107 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-fr_FR
2017-04-11 23:39:39,184 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-fr
2017-04-11 23:39:39,229 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-fr
2017-04-11 23:39:39,263 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
2017-04-11 23:39:39,347 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-fr_FR
2017-04-11 23:39:39,364 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 14 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:39:39,391 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-en
2017-04-11 23:39:39,436 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-fr
2017-04-11 23:39:39,514 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
2017-04-11 23:39:39,558 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-fr_FR
2017-04-11 23:39:39,608 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 15 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:39:39,723 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-fr
2017-04-11 23:39:39,847 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 16 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:39:39,885 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-en
2017-04-11 23:39:40,088 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 17 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:39:40,331 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 18 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:39:40,350 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-fr_FR
2017-04-11 23:39:40,574 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 19 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:39:40,595 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-fr
2017-04-11 23:39:40,816 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 20 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:39:40,842 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-en
2017-04-11 23:39:47,785 INFO     yunohost.hook <lambda> - [1144.174] 1 656 ko réceptionnés en 14s (112 ko/s)
2017-04-11 23:40:18,419 INFO     yunohost.hook <lambda> - [1144.174] Lecture des listes de paquets…
2017-04-11 23:40:18,437 WARNING  yunohost.hook <lambda> - [1144.174] W: Erreur de GPG : http://httpredir.debian.org jessie-backports InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
2017-04-11 23:40:18,476 INFO     yunohost.hook <lambda> - [1144.174] + sudo rm -f /etc/apt/sources.list.d/mongodb-org-3.2.list
2017-04-11 23:40:18,615 INFO     yunohost.hook <lambda> - [1144.174] + sudo apt-get update
2017-04-11 23:40:19,122 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie InRelease
2017-04-11 23:40:19,126 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://repo.yunohost.org jessie InRelease
2017-04-11 23:40:19,130 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie InRelease
2017-04-11 23:40:19,291 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 1 http://httpredir.debian.org jessie-backports InRelease [166 kB]
2017-04-11 23:40:19,391 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://repo.yunohost.org jessie/stable armhf Packages
2017-04-11 23:40:19,398 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie/main armhf Packages
2017-04-11 23:40:19,407 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/main armhf Packages
2017-04-11 23:40:19,500 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/contrib armhf Packages
2017-04-11 23:40:19,591 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://archive.raspberrypi.org jessie/ui armhf Packages
2017-04-11 23:40:19,602 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/non-free armhf Packages
2017-04-11 23:40:19,702 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports InRelease
2017-04-11 23:40:19,738 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://mirrordirector.raspbian.org jessie/rpi armhf Packages
2017-04-11 23:40:20,140 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://httpredir.debian.org jessie-backports/main Translation-en
2017-04-11 23:40:20,220 INFO     yunohost.hook <lambda> - [1144.174] Atteint http://httpredir.debian.org jessie-backports/main armhf Packages
2017-04-11 23:40:20,511 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-fr_FR
2017-04-11 23:40:20,602 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-fr
2017-04-11 23:40:20,676 INFO     yunohost.hook <lambda> - [1144.174] Ign http://repo.yunohost.org jessie/stable Translation-en
2017-04-11 23:40:20,845 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports/main Translation-fr_FR
2017-04-11 23:40:20,923 INFO     yunohost.hook <lambda> - [1144.174] Ign http://httpredir.debian.org jessie-backports/main Translation-fr
2017-04-11 23:40:21,479 INFO     yunohost.hook <lambda> - [1144.174] Atteint https://packages.gitlab.com jessie InRelease
2017-04-11 23:40:21,987 INFO     yunohost.hook <lambda> - [1144.174] Atteint https://packages.gitlab.com jessie/main Sources
2017-04-11 23:40:22,482 INFO     yunohost.hook <lambda> - [1144.174] Atteint https://packages.gitlab.com jessie/main armhf Packages
2017-04-11 23:40:22,706 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 2 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:40:22,935 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 3 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:40:23,168 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 4 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:40:23,395 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 5 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:40:23,628 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 6 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:40:23,830 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-fr_FR
2017-04-11 23:40:23,863 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 7 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:40:23,990 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-fr
2017-04-11 23:40:23,998 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-fr_FR
2017-04-11 23:40:24,081 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-fr
2017-04-11 23:40:24,088 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 8 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:40:24,154 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/main Translation-en
2017-04-11 23:40:24,162 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
2017-04-11 23:40:24,240 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-fr_FR
2017-04-11 23:40:24,321 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 9 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:40:24,326 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-fr_FR
2017-04-11 23:40:24,329 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-fr
2017-04-11 23:40:24,411 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/main Translation-en
2017-04-11 23:40:24,478 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-fr
2017-04-11 23:40:24,487 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-fr_FR
2017-04-11 23:40:24,544 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 10 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:40:24,581 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-fr
2017-04-11 23:40:24,650 INFO     yunohost.hook <lambda> - [1144.174] Ign http://archive.raspberrypi.org jessie/ui Translation-en
2017-04-11 23:40:24,657 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
2017-04-11 23:40:24,736 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-fr_FR
2017-04-11 23:40:24,773 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 11 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:40:24,830 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-fr
2017-04-11 23:40:24,910 INFO     yunohost.hook <lambda> - [1144.174] Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
2017-04-11 23:40:25,000 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 12 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:40:25,229 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 13 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:40:25,471 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 14 https://packages.gitlab.com jessie/main Translation-fr_FR [162 B]
2017-04-11 23:40:25,475 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-fr_FR
2017-04-11 23:40:25,704 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 15 https://packages.gitlab.com jessie/main Translation-fr [162 B]
2017-04-11 23:40:25,708 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-fr
2017-04-11 23:40:25,932 INFO     yunohost.hook <lambda> - [1144.174] Réception de : 16 https://packages.gitlab.com jessie/main Translation-en [162 B]
2017-04-11 23:40:25,936 INFO     yunohost.hook <lambda> - [1144.174] Ign https://packages.gitlab.com jessie/main Translation-en
2017-04-11 23:40:33,424 INFO     yunohost.hook <lambda> - [1144.174] 166 ko réceptionnés en 14s (11,6 ko/s)
2017-04-11 23:40:52,551 INFO     yunohost.hook <lambda> - [1144.174] Lecture des listes de paquets…
2017-04-11 23:40:52,569 WARNING  yunohost.hook <lambda> - [1144.174] W: Erreur de GPG : http://httpredir.debian.org jessie-backports InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
2017-04-11 23:40:52,607 INFO     yunohost.hook <lambda> - [1144.174] + remove_systemd_service
2017-04-11 23:40:52,614 INFO     yunohost.hook <lambda> - [1144.174] + sudo systemctl stop wekan
2017-04-11 23:40:52,731 WARNING  yunohost.hook <lambda> - [1144.174] Failed to stop wekan.service: Unit wekan.service not loaded.
2017-04-11 23:40:52,757 INFO     yunohost.hook <lambda> - [1144.174] + sudo systemctl disable wekan
2017-04-11 23:40:53,303 INFO     yunohost.hook <lambda> - [1144.174] + sudo rm -f /etc/systemd/system/wekan.service
2017-04-11 23:40:53,413 INFO     yunohost.hook <lambda> - [1144.174] + sudo systemctl daemon-reload
2017-04-11 23:40:53,898 INFO     yunohost.hook <lambda> - [1144.174] + remove_nginx_conf
2017-04-11 23:40:53,901 INFO     yunohost.hook <lambda> - [1144.174] + sudo rm -f /etc/nginx/conf.d/.d/wekan.conf
2017-04-11 23:40:54,020 INFO     yunohost.hook <lambda> - [1144.174] + sudo service nginx reload
2017-04-11 23:40:55,202 INFO     yunohost.hook <lambda> - [1144.174] + remove_user_wekan
2017-04-11 23:40:55,206 INFO     yunohost.hook <lambda> - [1144.174] ++ sudo getent passwd wekan
2017-04-11 23:40:55,324 INFO     yunohost.hook <lambda> - [1144.174] + [[ ! -z wekan:x:56955:56955::/home/wekan:/bin/bash ]]
2017-04-11 23:40:55,326 INFO     yunohost.hook <lambda> - [1144.174] + sudo userdel wekan
2017-04-11 23:40:56,429 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2017-04-11 23:40:56] "POST /apps HTTP/1.1" 500 159 1530.243115
```

**Comment by alexAubin** [comment]
Is this issue still relevant now that we used "pre-built" archives ?

**Comment by frju365** [comment]
Depend... is wekan for ARM ? Is there enough RAM and CPU for such app ? Perhaps add condition to prevent it from being installed on ARM, or at least warn the user.

**Comment by frju365** [comment]
Moreover, you added Enh tag... not sure it's only enh but perhaps bug.

**Comment by alexAubin** [comment]
That's a tough choice :thinking: 

![bug_or_feature](https://user-images.githubusercontent.com/4533074/36981545-bb99c6b0-208d-11e8-8a33-d139e4a2ebd4.jpg)

**Comment by alexAubin** [comment]
![cnxk6ev](https://user-images.githubusercontent.com/4533074/36981717-28843008-208e-11e8-9222-1792e4aedecd.png)

**Comment by Gredin67** [comment]
How is the status of wekan for ARM? I try to install it but it says that mongodb-org stuff is not installed.
Could it work properly on a Olimex lime1 (512Mb Ram)?

**Comment by alexAubin** [comment]
I think it could work yes, but we need to find a fix for the mongodb thing. I looked it up quickly the other day and saw that there might me ARMhf deb repo somewhere that could be used ... but I did not dig that further for now.

Feel free to have look, basically it's a matter of finding out what to put in the /etc/apt/sources.list thing to get mongodb to install on an ARM device, so thats ~relatively easy to test I guess :s

**Comment by Gredin67** [comment]
From what I've seen 64bits ARMv8 and greater are now officially supported by mongo as stated in
https://github.com/Barryrowe/mongo-arm
https://jira.mongodb.org/browse/SERVER-1811
But I think ARM64 is quite recent, and I know olimex Lime 1 with ARM Cortex-A8 is 32bits.
On archlinux for ARM the depository holds a version 3... that does not support ARM32. It could however be user for ARM64.
On raspbian depository, it seems like there are several versions including a 
`mongodb_2.4.14-4_armhf.deb  ` 
that could fit.
https://archive.raspbian.org/raspbian/pool/main/m/mongodb/

If any later version is required, there are several tutorial and links listed here
https://stackoverflow.com/questions/34569404/install-mongodb-version-3-raspberry-pi-2
including this tutorial
https://www.clarenceho.net/2015/12/building-mongodb-30x-for-arm-armv7l.html
ITs author later said 

> Arch Linux ARM latest build of MongoDB 3.2.0 seems to be working fine. Except that the default storage engine was compiled as WiredTiger although there is no 32-bit support from WiredTiger. You will need to add parameter --storageEngine=mmapv1

So first I'll try to install mongoDB from RaspBian
Second I'll try to install mongoDB from arch linux ARM depository with the parameter --storageEngine=mmapv1
And third with the above cited tutorial.

**Comment by Gredin67** [comment]
I did some testing. In fact mongoDB on raspbian repo is the same than that of debian repo : version 2.4.10 for armhf. The meta-package is called mongodb
Installation of wekan_ynh fails because it defines dependency to mongodb-org packages that correspond to version 3.2 that is not available for arm 32 bits (armhf?)  : 
http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2

I have some questions : 

- Where can I see if the version 3.2 is necessary to run wekan 8.9?
- If version 2.4 is fine, then can I simply remove the lines of the installation script adding the repo http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2 ? And change the dependency from mongodb-org packages to mongodb packages? Then I guess we would have to change the remove script accordingly.
- How to add a condition on the architecture : keep the current script for x86/64 architectures and use mongodb 2.4 for 32 bits architectures.

**Comment by alexAubin** [comment]
Some update on this. We discussed this topic a few weeks ago IRL with @Gredin67. What we found is that : 

- Nowadays, Wekan officially requires Mongodb 3.2. We could try to use previous mongodb version, but considering that Wekan evolves very quickly and that Mongodb 3.2 is already old (Mongodb is at 4.x on their website) this is very risky on the mid-term
- There is a weird website which apparently heavily use Mongodb on RPi : https://www.mongo-pi.com/resources - they apparently have builds for 3.0 and 3.4 (but not 3.2 lol) ... though I'm not even sure how to use those apart from extracting the bin in /usr/bin or so ...
- Mongodb only supports 64bit starting from 3.4. So no Wekan (in the future at least..) on 32 bit, which means no i386 and no armhf.
- Digging into this a bit today, I found that Mongo decided to support arm64 by somehow switching their stuff from Debian Jessie to Ubuntu Xenial ... which, doesn't make much sense to me but anyway (c.f. https://github.com/docker-library/mongo/pull/ 275). Anyway I was not able to find a proper/easy way to install Mongodb on Stretch ARM64...
- Also today, I found that there are some plan on Wekan's side to support ARM, or at least ARM64/AARCH64 here : https://blog.wekan.team/2018/01/wekan-progress-on-x64-and-arm/index.html

So to summarize : it's a complete mess, but there is hope ..?

Seeing how this is complicated, honestly right now I would say let's just add a check at the beginning of the install script that the architecture is amd64 and cancel the install otherwise... This is clearly disappointing but except if we have mongo wizards somewhere ready to help us, we can't maintain support on ARM just ourselves on the long run I think :/

**Comment by alexAubin** [comment]
Closing the issue, because Wekan doesn't support ARM so far :s 

Added a PR to propose an arch check at the beginning of the install : https://github.com/YunoHost-Apps/wekan_ynh/pull/27

**Comment by locness3** [comment]
Hey @frju365 @alexAubin @Gredin67 @zamentur,

it seems like [Wekan now supports ARM](https://github.com/wekan/wekan/wiki/Raspberry-Pi) (at least Raspberry Pi). I believe we should update the script to remove the check, if it does work ?

**Comment by yalh76** [comment]
Install script is already updated:
https://github.com/YunoHost-Apps/wekan_ynh/blob/3be3f1d7290b534f7689222645a42c06f3103589/scripts/install#L38-L43

Wekan is only provided for arm64

**Comment by locness3** [comment]
> Wekan is only provided for arm64

(You mean x86) But now it seems it **has** support for arm, see the link I provided

**Comment by Gredin67** [comment]
Hi, no he means arm64. There is support for x86, x64, ARM64 (raspberry 3) but not for ARMv7 (older raspberry)

Le 31 décembre 2019 10:49:37 GMT+01:00, Locness <notifications@github.com> a écrit :
>> Wekan is only provided for arm64
>
>(You mean x86) But now it seems it **has** support for arm, see the
>link I provided
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/wekan_ynh/issues/1#issuecomment-569899350

-- Envoyé de /e/ Mail.

**Comment by locness3** [comment]
Oh ok, I understand. But can't we update the script to have it work on arm64 ?

**Comment by yalh76** [comment]
> 
> 
> Oh ok, I understand. But can't we update the script to have it work on arm64 ?

Done since https://github.com/YunoHost-Apps/wekan_ynh/pull/44 9 july 2019

**Comment by locness3** [comment]
Hm, i have a pi 3 and it does not seem to work. I'll find if there is a way to update the apps list.

**Comment by locness3** [comment]
Still getting "Sorry, but this app can only be installed on a x86, 64 bits machine :("

**Comment by yalh76** [comment]
Can you provide the full installation logs ?

**Comment by locness3** [comment]
https://paste.yunohost.org/raw/coruzohiyo

**Comment by yalh76** [comment]
OK, what is the result for `uname -a` ?

**Comment by locness3** [comment]
```
Linux locness.hopto.org 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by locness3** [comment]
But I think the problem comes from here :
https://github.com/YunoHost-Apps/wekan_ynh/blob/3be3f1d7290b534f7689222645a42c06f3103589/scripts/install#L40
It's checking if the architecture is arm, which is arm64 AND armv7 I guess ? So I'm pretty sure we should just detect armv7 isntead of arm

**Comment by yalh76** [comment]
`$architecture` is initialized with https://github.com/YunoHost-Apps/wekan_ynh/blob/master/scripts/ynh_detect_arch__2

So your YunoHost is detected as arm not arm64. So maybe your YunoHost is 32 bits instead of 64 bits.

What is the result for: `lscpu`

**Comment by locness3** [comment]
Wait, just saw "armv7l" in the previous comment input. But it's a raspberry pi 3, and seeing your comment raspberry pi 3s are `arm64`..

Anyway, `lscpu` :
```
Architecture:          armv7l                                                                                                 
Byte Order:            Little Endian                                                                                          
CPU(s):                4                                                                                                      
On-line CPU(s) list:   0-3                                                                                                    
Thread(s) per core:    1                                                                                                      
Core(s) per socket:    4                                                                                                      
Socket(s):             1                                                                                                      
Model:                 4                                                                                                      
Model name:            ARMv7 Processor rev 4 (v7l)                                                                            
CPU max MHz:           1200.0000                                                                                              
CPU min MHz:           600.0000                                                                                               
BogoMIPS:              38.40                                                                                                  
Flags:                 half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32                
```

**Comment by yalh76** [comment]
Seems that arm 7 is 32 bit, it's why you can't install wekan_ynh

BTW: I'm not a Raspberry Pi nor Linux specialist

**Comment by locness3** [comment]
Well, ok :/
